# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "ata_piix"
        "uhci_hcd"
        "virtio_pci"
        "sr_mod"
        "virtio_blk"
      ];
      kernelModules = [ ];

    };
    kernelModules = [ ];
    extraModulePackages = [ ];

  };

  # TODO: change this to your /etc/nixos/hardware-configuration.nix stuff
  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/920510e9-8798-469c-ab18-02169dc7eea8";
  #     fsType = "ext4";
  #   };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/df286d25-4ce5-444c-9ed0-7ee5f9a1d8fb"; }
  #   ];

  # Enabless DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
